from typing import Any

from pydantic import BaseModel, Field

from app.models.cricket import LeaderboardEntry


class ELI5Response(BaseModel):
    explanation: str = Field(
        description="Plain English explanation generated by the LLM",
    )
    raw_data: Any = Field(
        description="The underlying data the explanation was based on",
    )


class ChatResponse(BaseModel):
    reply: str = Field(description="The assistant's reply message")


class LeaderboardELI5Response(BaseModel):
    entries: list[LeaderboardEntry] = Field(description="Ranked leaderboard entries")
    summary: str = Field(description="Plain English summary of the leaderboard")
